### ISSUE TITLE
If you turn the server OFF all of your skills keep in level 10

### ISSUE THREAD

**Issue by bananasplinter96** [AguirreMoy/Stardew-Multiplayer-Server-Mod#2]
if you turn the server OFF and try to play with your character all of your skills are in 10 and I couldn't find a way to revert this or reset the skills of the character.

I was looking in the source code into the /**ModEntry.cs**, and I think I found the lines that have the problem.

In some lines, it orders to save the current skills of the player in a _.json_ file when you start the server and change these in-game to level 10 **(Stardew-Multiplayer-Server-Mod/Always On Server/ModEntry.cs line _134_)**.

However, when you turn it OFF the server doesn't turn back the character skills to the info that was saved in the _.json_ file **(Stardew-Multiplayer-Server-Mod/Always On Server/ModEntry.cs. line _308_)**. But! Into the syntax of the code, you can see the command lines to restore the skills using the information saved in the _.json_ file when you turn the server OFF.

I was wondering if someone with more knowledge about **C#** could solve this.

Note: I also tested modifying the save-game data file, and I saw that the JSON file saves the info about the skills that I put in the save-game data and keeps the information on it, however, when you start the server all of the in-game skills turn to level 10 without modifying the JSON file.

**Comment by AguirreMoy** [comment]
Addressed in https://github.com/AguirreMoy/Stardew-Multiplayer-Server-Mod/pull/4
