### ISSUE TITLE
[BUG] No keyboard inputs register when in automatic mode with no clients connected.

### ISSUE THREAD

**Issue by perkmi** [AguirreMoy/Stardew-Multiplayer-Server-Mod#3]
**Describe the bug**
When in automatic mode with no clients connected keyboard input are not registered, so once you press F9 to enter automatic mode you can not press it again to exit automatic mode. I'm on Linux so I don't know if this happens in Windows too.

**To Reproduce**
1. Start the game with no other clients connected and wait for 6:10
2. Press F9 to enter automatic mode and wait 3 seconds
3. Can't press F9 again to exit automatic mode

**Expected behavior**
F9 both enters and exits automatic mode

**Desktop (please complete the following information):**
 - Version 1.6.3
 - Linux

**Additional context**
I just found out this repo existed and I already made the fix for this in a fork of the original repo. I can't create a pull request I think because the repo name changed, but my fix for this is in ModEntry.cs here: https://github.com/perkmi/Always-On-Server-for-Multiplayer It was fixed in this commit: https://github.com/perkmi/Always-On-Server-for-Multiplayer/commit/3bbb6f90c43d42af84843d42903676bf244ab0a9

**Comment by AguirreMoy** [comment]
Nice fix, do you want to try forking and submitting the PR or do you not mind me just copy pasting it? Just want to make sure you get your credit.

**Comment by perkmi** [comment]
I don't mind if you just copy paste it, but I can create a proper PR since I also have a fix for a bug (at least in Linux) where the host can get stuck in a locked state constantly trying to skip an event.

**Comment by perkmi** [comment]
Fixed with https://github.com/AguirreMoy/Stardew-Multiplayer-Server-Mod/pull/6
